version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8888:8888
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    tty: true